name: Release

on:
    push:
        tags:
            - v*

jobs:
    release:
        name: Release
        runs-on: ubuntu-20.04
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   uses: actions/setup-go@v5
                with:
                    go-version: '^1.22'
            -   name: Install dependencies
                run: sudo apt update && sudo apt install libsnmp-dev
            -   name: GoReleaser
                uses: goreleaser/goreleaser-action@v5
                with:
                    args: release
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
