name: Release

on:
    push:
        tags:
            - v*

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   uses: actions/setup-go@v2
            -   name: Install dependencies
                run: sudo apt update && sudo apt install libsnmp-dev
            -   name: GoReleaser
                uses: goreleaser/goreleaser-action@v2
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
